### PR TITLE
Created Json File from reducer

### PR DESCRIPTION
**Pull request by Jpfonseca**
Hi just created the Json file has requested on #95. 
Check if it is as  you want it.

### CODE REVIEW

**Comment by papistan** [comment]
Close but It needs to be called and returned as an object within the reducer decks. Then test locally to ensure it works. Thanks

**Comment by Gangezilla** [comment]
Nice job @Jpfonseca, it probably shouldn't be in the reducers folder either, doesn't really fit in with what a reducer is in the redux mentality. Might be worthwhile pulling it out into a separate data folder or something.

**Comment by Jpfonseca** [comment]
Don't Merge!!!

 @papistan , @Gangezilla   I need help refactoring the dependencies
Right now the only mistake I get is : 

`Uncaught TypeError: Cannot read property 'map' of undefined
    at DeckList.renderList (bundle.js:21842)
    at DeckList.render (bundle.js:21878)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (bundle.js:7775)
    at ReactCompositeComponentWrapper._renderValidatedComponent (bundle.js:7795)
    at ReactCompositeComponentWrapper.wrapper [as _renderValidatedComponent] (bundle.js:1526)
    at ReactCompositeComponentWrapper.mountComponent (bundle.js:7408)
    at ReactCompositeComponentWrapper.wrapper [as mountComponent] (bundle.js:1526)
    at Object.mountComponent (bundle.js:5718)
    at ReactCompositeComponentWrapper.mountComponent (bundle.js:7413)
    at ReactCompositeComponentWrapper.wrapper [as mountComponent] (bundle.js:1526)`

**Comment by Gangezilla** [comment]
@Jpfonseca hey mate, i have a feeling its failing at `src/containers/deck_list.js`, line 21. Looks like it's trying to map over all of the cards but it doesn't have them available to do so. I think you'll need to import the cards in from your JSON file and then map over it from there. Does that help? Let me know if I can help some more

**Comment by papistan** [comment]
@Jpfonseca I'm going to work on this issue now, so closing this pr

**Pull request closed without merging**
