### PR TITLE
feat(linting): Add .eslint file to begin enforcing standards

### PR DESCRIPTION
**Pull request by Gangezilla**
Hey @papistan, I've added an eslint file so this way we can avoid issues like inconsistent spacing, and we can begin having some standard coding practices across all your contributors. This is a pretty standard AirBnb eslint setup, with a few additional things in it too. Let me know if you think this is useful/something you're interested in. I think it would be good especially with the high number of contributors you're getting.

Thanks 🎉

### CODE REVIEW

**Comment by Gangezilla** [comment]
PS: There's a bunch of existing lint errors in the codebase, but they can be fixed up in another PR I think 👍

**Comment by nveenjain** [comment]
Could you delete package-lock.json file, it's created by default by npm (v5+), it is not required though. :)

**Comment by Gangezilla** [comment]
Yup! Sure mate :)

**Comment by papistan** [comment]
@Gangezilla @nveenjain awesome. thanks for thinking of this. I've yet to incorporate eslint (shame on me), but the times I've used it it was the airbnb version, so sounds good.

**Comment by Gangezilla** [comment]
Haha, I'll forgive you this time mate. I'm a big fan of it. Bonus tip: If you're using VSCode, you can add this into your preferences `"eslint.autoFixOnSave": true` and it'll fix your lint errors on save automatically, it's a great time saver.

**Comment by nveenjain** [comment]
@papistan, could you please look into #99, I updated gitignore to prevent future addition of package-lock file. And all credit for thinking about linting goes to @gangezilla, I just reviewed the PR 😅

**Pull request merged**
