### PR TITLE
Added a question in Javascript Core concepts, fixed a typo.

### PR DESCRIPTION
**Pull request by hardikyjoshi**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Fixed a typo and added a new question to Javascript Core Concepts

* **What is the current behavior?** (You can also link to an open issue here)
A new question is added

* **What is the new behavior (if this is a feature change)?**
New question to Javascript Core Concepts

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:
I'm a first-time contributor, hence I'm unaware as to whether we need to commit bundle.js as part of the PR. Thank you!

### CODE REVIEW

**Comment by hardikyjoshi** [comment]
@papistan Do we need to add bundle.js as part of our PR?

**Comment by jaimellamasi** [comment]
@hardikyjoshi bundle.js shouldn't be part of any PR. It's the output once the project is compiled. It should be included in the .gitignore

**Comment by hardikyjoshi** [comment]
@jllamasi Sure, I'll revert that and commit my necessary changes 👍 Thanks! :)

**Comment by hardikyjoshi** [comment]
@jllamasi updated the PR. Thanks!

**Pull request merged**
