### PR TITLE
Update reducer_decks.js

### PR DESCRIPTION
**Pull request by kunalvishnoi**
#12  #11  Questions added of html and css

### CODE REVIEW

**Comment by kunalvishnoi** [comment]
level of questions are good? or add some more questions? @papistan

**Comment by papistan** [comment]
@kunalvishnoi thanks for contributing. HTML questions are good, opacity one too micro-level, but perhaps a question about what opacity in general? You're PR deletes a lot of questions. If you can update your master version and add the questions back in after an hour that would be great (without deleting others questions). Thanks!

**Comment by kunalvishnoi** [comment]
it means i have to add my questions again and send a new PR? @papistan

**Comment by kunalvishnoi** [comment]
Again send a PR.

**Pull request closed without merging**
